### ISSUE TITLE
process.env is undefined

### ISSUE THREAD

**Issue by jetonk** [fxnoob/chrome-extension-boilerplate#40]
With this boilerplate I can't access process.env it says undefined.

**Comment by fxnoob** [comment]
Ahh very late to this.
Thanks for Idea. it can be configured. 
see:https://stackoverflow.com/questions/46224986/how-to-pass-env-file-variables-to-webpack-config
Would you like to submit a PR?

**Comment by jetonk** [comment]
@fxnoob I found a solution for this, I will submit a PR for this of course, thank you for your reply anyway.
